spring:
  datasource:
    url: jdbc:mysql://localhost/security-overview
    username: root
    password: 1q2w3e
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        proc:
          param_null_passing: true
        check_nullability: true
